
import { Button, LineEdit, VerticalBox, HorizontalBox, TextEdit, ScrollView } from "std-widgets.slint";

export struct MessageModel {
    sender: string,
    message: string,
}

export struct RoomModel {
    id: string,
    name: string,
}

export struct VisibleRoomModel {
    room_id: string,
    complete: bool,
    messages: [MessageModel],
}

component RoomSelector {
    callback show_room(room_id: string);
    in-out property<[RoomModel]> list-of-rooms;

    VerticalBox {
        alignment: start;
        for room in root.list-of-rooms: room-list := Button {
           text: room.name;
           clicked => {
             root.show_room(room.id);
           }}
    }
}

component Message {
    in property<MessageModel> message;

    HorizontalBox {
        Rectangle {
            HorizontalBox {
                Text {
                    text: "\{root.message.sender}:";
                }
            }
        }
        Rectangle {
            background: #b5b5b5;
            border-radius: 5px;
            width: 100%;
            HorizontalBox {
                Text {
                    text: root.message.message;
                    wrap: word-wrap;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    callback show_room(room_id: string);
    callback send_message(message: string);

    in-out property<[RoomModel]> list-of-rooms;
    in-out property<VisibleRoomModel> visible-room;

    min-height: 300px;
    min-width: 800px;

    HorizontalBox {
        ScrollView {
            max-width: 300px;
            HorizontalBox {
            RoomSelector {
                list-of-rooms: list-of-rooms;
                show_room(id) => {
                    root.show_room(id);
                }
            }
            }
        }
        Rectangle {
            background: #d5d5d5;
            border-radius: 5px;
            VerticalBox {
                ScrollView {
                    // viewport-height: 300px;
                    // viewport-width: 300px;
                    // height: 200px;
                    // width: 200px;
                    VerticalBox {
                        alignment: start;
                        for message in root.visible-room.messages: message-list := Message {
                            message: message;
                        }
                    }

                    scrolled() => {
                        if self.viewport-y > -200px && root.visible-room.complete == false {
                            debug("viewport-y: ", self.viewport-y);
                        }
                    }
                }

                editor := LineEdit {
                    accepted(text) => {
                        root.send_message(text);
                        editor.text = "";
                    }
                }
            }
        }
    }
}
