
import { Button, LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";

export struct MessageModel {
    sender: string,
    message: string,
}

export component MainWindow inherits Window {
    in-out property<[MessageModel]> list-of-messages;

    VerticalBox {
        Text {
            text: "You have logged in to a matrix homeserver";
        }
        for message in root.list-of-messages: message-list := HorizontalBox {
            Text {
                text: message.sender;
            }
            Text {
                text: message.message;
            }
        }
    }
}
