import { Button, LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component PasswordLoginWindow inherits Window {
    callback login(username: string, password: string);
    VerticalBox {
        HorizontalBox {
            Text {
                text: "Username: ";
                vertical-alignment: center;
            }

            usernameField := LineEdit {
                placeholder-text: "@dude:matrix.org";
            }
        }

        HorizontalBox {
            Text {
                text: "Password: ";
                vertical-alignment: center;
            }

            passwordField := LineEdit {
                input-type: password;
            }
        }

        Button {
            text: "Login";
            clicked => {
                root.login(usernameField.text, passwordField.text);
            }
        }
    }
}
